# Site Settings
locale                   : "en-US"
title                    : "Rumana Yasmin"
title_separator          : "-"
name                     : &name "Rumana Yasmin"
description              : &description "Lecturer in CSE | AI, Machine Learning, Computer Vision"
url                      : https://rumana26.github.io
baseurl                  : ""
repository               : "rumana26/rumana26.github.io"
 
# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :
 
# Site Author
author:
  name             : "Rumana Yasmin"
  avatar           : "images/profile.jpg"
  bio              : "Lecturer in Computer Science & Engineering at Bangladesh University of Professionals (BUP). Research interests: Machine Learning, Computer Vision, NLP, Graph Neural Networks, Explainable AI."
  location         : "Dhaka, Bangladesh"
  employer         : "Bangladesh University of Professionals"
  pubmed           :
  googlescholar    : "https://scholar.google.com/citations?user=6DCAdz4AAAAJ&hl=en"
  email            : "rumana.yasmin@bup.edu.bd"
  researchgate     : "https://www.researchgate.net/profile/Rumana-Yasmin-3"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "rumana26"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         :
  orcid            : "https://orcid.org/0009-0003-5599-5447"
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
  scopus           : "https://www.scopus.com/authid/detail.uri?authorId=57346800600"
 
# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
 
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
 
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
 
# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
 
# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
 
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
 
# Outputting
permalink: /:categories/:title/
timezone: Asia/Dhaka
 
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
 
# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
